"""trying something

Revision ID: 0fee637d3f76
Revises: a8f139488e08
Create Date: 2025-02-24 19:44:49.123280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fee637d3f76'
down_revision = 'a8f139488e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.drop_constraint('bookings_billing_id_fkey', type_='foreignkey')
        batch_op.drop_column('billing_id')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('billing_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('bookings_billing_id_fkey', 'billings', ['billing_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('booking_date')

    # ### end Alembic commands ###
