"""empty message

Revision ID: 312677a8472e
Revises: 385c899a10bf
Create Date: 2025-03-02 17:23:00.947742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312677a8472e'
down_revision = '385c899a10bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('billings_package_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'package', ['package_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('billings_package_id_fkey', 'package', ['package_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
