"""empty message

Revision ID: 385c899a10bf
Revises: b9df1278cea0
Create Date: 2025-02-26 21:39:22.657462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385c899a10bf'
down_revision = 'b9df1278cea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('billings_package_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'package', ['package_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('billings_package_id_fkey', 'package', ['package_id'], ['id'])
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
