"""trying part 2

Revision ID: 5c7f2a8fc78c
Revises: 0fee637d3f76
Create Date: 2025-02-24 19:47:36.285782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7f2a8fc78c'
down_revision = '0fee637d3f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'billings', ['billing_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('billing_id')

    # ### end Alembic commands ###
