"""returned it

Revision ID: a8f139488e08
Revises: eb4d0ca3e34c
Create Date: 2025-02-24 18:30:12.630078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f139488e08'
down_revision = 'eb4d0ca3e34c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.drop_constraint('billings_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('billings_package_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('package_id')
        batch_op.drop_column('amount')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('amount')

    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('billings_package_id_fkey', 'package', ['package_id'], ['id'])
        batch_op.create_foreign_key('billings_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
